### ISSUE TITLE
Fully move from pyglet to visbrain

### ISSUE THREAD

**Issue by alexpron** [brain-slam/slam#60]
Visbrain was chosen as the visualisation package for slam. 
+ example_surface_profiling; current pyglet display should be done using visbrain
+ example_curvature_direction: current display calls matplotlib, visbrain implementation would be great

Furthermore, it would be the opportunity to discuss how to deal with visualisation dependence in the example and strategies that could be implemented

**Comment by JulienLefevreMars** [comment]
Yo Alex ! 

For curvature direction I have everything for that in visbrain :-) There remains some tricky issues because there are troubles with vispy to manage a surface and vectors. The opacity of the mesh is lost and it is a big mess. See here for instance:
https://github.com/EtienneCmb/visbrain/issues/84

I have found a temporary solution where points that are not visible from the camera location are hidden but it is not completely satisfactory. The best way would consist to use ray tracing to identify point that are really not visible (not based on a criterion with the vertex normals, whose only advantage is to be less costfull).

Bon réveillon !
Julien

**Comment by alexpron** [comment]
Super nice @JulienLefevreMars !  That definetly is a super basis to work on to have the final display we want. May be worth to discuss with @EtienneCmb next year :)  Bon réveillon et à bientôt

**Comment by EtienneCmb** [comment]
Hello guys ! Happy new year :D

Sorry for the delay @JulienLefevreMars, but very nice figures !

Under the hood the [VectorObj](https://github.com/EtienneCmb/visbrain/blob/master/visbrain/objects/vector_obj.py#L198) is using the [ArrowVisual](https://github.com/vispy/vispy/blob/master/vispy/visuals/line/arrow.py#L103) Vispy class. The vector  is built using two elements : the line and the arrow head. The best would be to have a custom glsl shaders where the arrow is hidden when the camera is moving. From what I remember, the shaders should contain a `discard` so that, given a certain condition, we don't plot the arrow according to the camera rotation. I suggest to open a issue on Vispy github where you can past the figures to illustrate the problem, they might have a better solution
